/**
 * Runtime sprite recoloring for Among Gas.
 *
 * The Red player sprites are the canonical base loaded from disk.
 * Every other color is generated by remapping red-dominant pixels
 * to the chosen player color — preserving black outlines, the white
 * visor, and all non-body details — so a single set of art assets
 * produces all 12 color variants with correct shading.
 *
 * Usage:
 *   import { recolorCanvas, PLAYER_COLORS } from './SpriteRecolor';
 *   const canvas = recolorCanvas(htmlImageElement, PLAYER_COLORS['blue']);
 *   scene.textures.addCanvas('blue_down_1', canvas);
 */

export type RGB = [number, number, number];

/**
 * Official Among Gas player color palette (matches original game).
 * Red is the base loaded from Assets; all others are generated at runtime.
 */
export const PLAYER_COLORS: Record<string, RGB> = {
  red:    [197,  17,  17],
  blue:   [ 19,  46, 209],
  green:  [ 19, 128,  44],
  pink:   [238,  84, 187],
  orange: [240, 125,  13],
  yellow: [246, 246,  87],
  black:  [ 63,  71,  78],
  white:  [214, 224, 240],
  purple: [107,  47, 188],
  brown:  [113,  73,  30],
  cyan:   [ 56, 254, 220],
  lime:   [ 80, 240,  57],
};

/**
 * Shadow shade: ~55% brightness of the main color.
 * This matches the dark-red shadow areas in the Red base sprite
 * (197 × 0.55 ≈ 108).
 */
export function shadowOf([r, g, b]: RGB): RGB {
  return [(r * 0.55) | 0, (g * 0.55) | 0, (b * 0.55) | 0];
}

/**
 * Recolor `src` so that:
 *  • Bright red-dominant pixels (R ≥ 120, R > G+50, R > B+50)
 *      → `target` color, brightness-scaled (reference: R=197 = full red)
 *  • Dark red-dominant pixels  (30 ≤ R < 120, R > G+50, R > B+50)
 *      → shadow of `target`, brightness-scaled (reference: R=108 ≈ 197×0.55)
 *  • All other pixels (black outlines, white visor, backpack, etc.)
 *      → unchanged
 *
 * Returns a new HTMLCanvasElement ready for `textures.addCanvas()`.
 * The recolored canvas is cached by the caller — call once per color+frame.
 */
/**
 * Fix the Red sprite artwork specifically: the Red sprites in Assets/ have a
 * blue backpack and a green visor — inconsistent with every other color which
 * has a matching backpack and a white/grey visor.
 *
 * This pass replaces:
 *  • Blue-dominant pixels (backpack) → red, brightness-scaled
 *  • Green-dominant pixels (visor)   → white/grey (#D8E0EB), brightness-scaled
 *  • Everything else (red body, black outlines, white highlights) → unchanged
 *
 * Returns a new HTMLCanvasElement ready for textures.addCanvas().
 */
export function fixRedSprite(
  src: HTMLImageElement | HTMLCanvasElement,
): HTMLCanvasElement {
  const w = ('naturalWidth'  in src ? src.naturalWidth  : src.width)  || 1;
  const h = ('naturalHeight' in src ? src.naturalHeight : src.height) || 1;

  const out = document.createElement('canvas');
  out.width  = w;
  out.height = h;

  const ctx = out.getContext('2d')!;
  ctx.drawImage(src, 0, 0);

  const id = ctx.getImageData(0, 0, w, h);
  const d  = id.data;

  // Target visor colour — matches the white/grey visor on all other characters
  const VISOR: RGB = [216, 224, 240];

  for (let i = 0; i < d.length; i += 4) {
    const r = d[i], g = d[i + 1], b = d[i + 2], a = d[i + 3];
    if (a < 10) continue;

    if (b > r + 60 && b > g + 40) {
      // Blue-dominant → backpack → remap to red, scaling brightness from b
      // reference max backpack blue ≈ 210
      const br = b / 210;
      d[i]     = Math.min(255, (197 * br + 0.5) | 0); // red body reference = 197
      d[i + 1] = Math.min(255, ( 17 * br + 0.5) | 0);
      d[i + 2] = Math.min(255, ( 17 * br + 0.5) | 0);
    } else if (g > r + 50 && g > b + 40) {
      // Green-dominant → visor → remap to white/grey, scaling from g
      // reference max visor green ≈ 200
      const br = g / 200;
      d[i]     = Math.min(255, (VISOR[0] * br + 0.5) | 0);
      d[i + 1] = Math.min(255, (VISOR[1] * br + 0.5) | 0);
      d[i + 2] = Math.min(255, (VISOR[2] * br + 0.5) | 0);
    }
    // Otherwise: red body, black outlines, white highlights → unchanged
  }

  ctx.putImageData(id, 0, 0);
  return out;
}

export function recolorCanvas(
  src: HTMLImageElement | HTMLCanvasElement,
  target: RGB,
): HTMLCanvasElement {
  const w = ('naturalWidth'  in src ? src.naturalWidth  : src.width)  || 1;
  const h = ('naturalHeight' in src ? src.naturalHeight : src.height) || 1;

  const out = document.createElement('canvas');
  out.width  = w;
  out.height = h;

  const ctx = out.getContext('2d')!;
  ctx.drawImage(src, 0, 0);

  const [tr, tg, tb] = target;
  const [sr, sg, sb] = shadowOf(target);

  const id = ctx.getImageData(0, 0, w, h);
  const d  = id.data;

  for (let i = 0; i < d.length; i += 4) {
    const r = d[i], g = d[i + 1], b = d[i + 2], a = d[i + 3];
    if (a < 10) continue; // fully transparent

    // Red-dominant: R channel well above both G and B
    if (r > g + 50 && r > b + 50) {
      if (r >= 120) {
        // Bright body — scale brightness relative to full red (197)
        const br = r / 197;
        d[i]     = Math.min(255, (tr * br + 0.5) | 0);
        d[i + 1] = Math.min(255, (tg * br + 0.5) | 0);
        d[i + 2] = Math.min(255, (tb * br + 0.5) | 0);
      } else if (r >= 30) {
        // Dark shadow body — scale relative to shadow red reference (108)
        const br = r / 108;
        d[i]     = Math.min(255, (sr * br + 0.5) | 0);
        d[i + 1] = Math.min(255, (sg * br + 0.5) | 0);
        d[i + 2] = Math.min(255, (sb * br + 0.5) | 0);
      }
      // r < 30 and red-dominant → near-black outline → leave unchanged
    }
    // Non-red-dominant → black outlines, white visor, grey backpack → unchanged
  }

  ctx.putImageData(id, 0, 0);
  return out;
}
